/*创建 订单表 t_Order*/

DROP TABLE IF EXISTS t_Order;

CREATE TABLE IF NOT EXISTS t_Order(
  Id CHAR(36) PRIMARY KEY,
  OrderNo VARCHAR(30) NOT NULL,
  CustomerId CHAR(36) NOT NULL,
  State CHAR(1) NOT NULL DEFAULT 1,
  Payment DECIMAL NOT NULL,
  UpdatedDate DATETIME NOT NULL DEFAULT  NOW(),
  CreatedDate DATETIME NOT NULL DEFAULT  NOW()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;