/*创建 商品表 t_Product*/

DROP TABLE IF EXISTS t_Product;

CREATE TABLE IF NOT EXISTS t_Product(
  Id CHAR(36) PRIMARY KEY,
  ProductName VARCHAR(100) NOT NULL,
  Brand VARCHAR(50) NULL,
  Price DECIMAL NOT NULL DEFAULT 0,
  Thumbnail VARCHAR(200)  NULL,
  Habitat VARCHAR(30) NULL,
  Tags VARCHAR(200) NULL,
  State CHAR(1) NOT NULL DEFAULT 1,
  Description VARCHAR(100) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT  NOW()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;