/*创建 角色表 t_Role*/

DROP TABLE IF EXISTS t_Role;

CREATE TABLE IF NOT EXISTS t_Role(
  Id CHAR(36) PRIMARY KEY,
  RoleName VARCHAR(50) NOT NULL,
  State CHAR(1) NOT NULL DEFAULT 1,
  CreatedDate DATETIME NOT NULL DEFAULT  NOW()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;